version: '20.10'

services:
  mysql-db:
    image: mysql:latest
    container_name: college_library
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./data:/var/lib/mysql
    